aws_profile: dev-profile
region: us-east-1
teams:
  backend:
    stacks:
      - name: api-stack
        template: templates/api.yaml
        parameters:
          DB_PASSWORD: SECRET:/dev/backend/db_password
          ENV: dev
  frontend:
    stacks:
      - name: web-stack
        template: templates/web.yaml
        parameters:
          API_URL: SSM:/dev/backend/api_url
