aws_profile: test-profile
region: us-east-1
teams:
  TeamA:
    stacks:
      - name: VPC
        template: templates/vpc.yaml
        parameters:
          serviceName: ""
          CidrBlock: ""
      - name: PublicSubnets
        template: templates/public-subnets.yaml
        parameters:
          serviceName: ""
          Sub0CIDR: ""
          Sub1CIDR: ""
          Sub2CIDR: ""
          tgwID: ""
      - name: PrivateSubnets
        template: templates/private-subnets.yaml
        parameters:
          serviceName: ""
          Sub0CIDR: ""
          Sub1CIDR: ""
          Sub2CIDR: ""
          tgwID: ""
      - name: RDSSubnets
        template: templates/rds-subnets.yaml
        parameters:
          serviceName: ""
          Sub0CIDR: ""
          Sub1CIDR: ""
          Sub2CIDR: ""
      - name: EKSSubnets
        template: templates/eks-subnets.yaml
        parameters:
          serviceName: ""
          Sub0CIDR: ""
          Sub1CIDR: ""
          Sub2CIDR: ""
          Sub3CIDR: ""
          Sub4CIDR: ""
          Sub5CIDR: ""
          tgwID: ""
      - name: SecurityGroups
        template: templates/security-groups.yaml
        parameters:
          serviceName: ""
      - name: EKS
        template: templates/eks.yaml
        parameters:
          ClusterName: ""
          Version: ""
          ServiceName: ""
          VpcId: ""
      - name: EFS
        template: templates/efs.yaml
        parameters:
          serviceName: ""
          clusterName: ""
      - name: S3
        template: templates/s3.yaml
        parameters:
          serviceName: ""
          clusterName: ""
